### ISSUE TITLE
Theme switch (dark / light) bug (on our website)

### ISSUE THREAD

**Issue by khalilcodes** [flowershow/flowershow#386] opened 2023-01-20 12:29 UTC
The theme toggle does not switch the theme to dark / light mode as expected.

## Acceptance
- [ ] Theme switch toggle works

## Tasks
- [ ] Find the root cause
- [ ] ...

**Comment by PhilippeduPreez** [comment] 2023-01-24 07:08
@khalilcodes I have not found the cause of this yet so just updating so far

The theme switch works with sites created with npx flowershow@latest install, so I think the bug might be in our template and not core

**Comment by olayway** [comment] 2023-01-24 13:19
@PhilippeduPreez I think you're right. And I think it's not even related to our template but rather pnpm hoisting behavior.

![image](https://user-images.githubusercontent.com/52197250/214304390-32914016-b163-4bd9-b4e4-294e506ab452.png)

It looks like `template` and `core` are using two different `next-themes` instances, so `useTheme` and `theme` accessed in core's `ThemeSelector` are not the same as the ones provided by the `ThemeProvider` used in template's `_app.tsx`. But I'm not 100% yet.

cc: @khalilcodes

**Comment by olayway** [comment] 2023-01-24 13:49
Ok, I've managed to make it work by turning off auto-installing peer dependencies and adding dummy declaration file (not yet sure why needed) in the core package for `next-themes`. But now I'm getting this error (even though the app starts and the theme switching works):

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/ola/Projects/lifeitself/flowershow/packages/template/.env
ConfigReadError (/home/ola/Projects/lifeitself/flowershow/packages/template/contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'next-themes' imported from /home/ola/Projects/lifeitself/flowershow/packages/core/dist/index.js
Did you mean to import next-themes@0.2.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/next-themes/dist/index.js?
event - compiled client and server successfully in 12.8s (3872 modules)
```

**Comment by khalilcodes** [comment] 2023-01-24 15:17
@olayway @PhilippeduPreez some docs on netlify with nextjs pnpm hoisting https://docs.netlify.com/integrations/frameworks/next-js/overview/#pnpm-support

**Comment by olayway** [comment] 2023-02-02 13:17
Moving this to current sprint and bumping priority as it's hard to develop without being able to preview light and dark theme versions.

**Comment by khalilcodes** [comment] 2023-02-02 20:55
I suggest we work on it while working on other tasks, as I did the same while doing page comments but with less focus on it so it doesn't block. Whoever gets it working then that's great. 😃

**Comment by olayway** [comment] 2023-02-14 12:12
This is actually pretty important thing to solve, as it's hard to even test locally how things look on light vs dark theme.

**Comment by khalilcodes** [comment] 2023-02-21 15:29
@PhilippeduPreez good find, the build fails though. But I think we can then export the `ThemeProvider` from core and use that maybe ? eg. `import { ThemeProvider } from @flowershow/core`

**Comment by PhilippeduPreez** [comment] 2023-02-21 16:26
@khalilcodes Exporting ThemeProvider from core seems to fix the build from failing, I'll open a PR for this

**Comment by khalilcodes** [comment] 2023-02-27 12:50
@PhilippeduPreez @olayway as I was working on Search fix I updated all the dependencies and peer-deps to latest in both core and template and it fixed the theme switch 🤷

**Comment by olayway** [comment] 2023-02-27 16:36
@khalilcodes actually I think moving it to core is a good idea anyway, so we'll go with Philippe's solution :)

**Closed** 2023-02-27 17:16 UTC
Labels: bug, Stream: App
